/**
 * Task 4.1 — Generate a typed `.d.ts` for `ctx.vars` from solidactions.yaml
 * declarations.
 *
 * Callers supply a `VarsDeclarations` (produced by `parseDeclarations`) and
 * receive a string of valid TypeScript declaration source. Writing this string
 * alongside the user's workflow source files enables their editor and tsc to
 * enforce that `ctx.vars.MY_FLAG` is `string` and `ctx.vars.GCAL` is
 * `ConnectionVar`.
 *
 * Augmentation mechanism:
 *   The generated file extends `InvokeCtxVarsAugment` — a purposely-empty
 *   interface exported from `@solidactions/sdk`. The hook exploits TypeScript
 *   declaration merging: a user's `.d.ts` that does:
 *
 *     declare module '@solidactions/sdk' {
 *       interface InvokeCtxVarsAugment { MY_FLAG: string; }
 *     }
 *
 *   merges `MY_FLAG: string` into `InvokeCtxVarsAugment`, which is intersected
 *   with `Record<string, VarValue>` in `InvokeCtx.vars`. Users without a
 *   generated file see the permissive `Record<string, VarValue>` fallback —
 *   zero regression for existing code.
 */

import type { VarsDeclarations } from './declarations';

const BANNER = `// Auto-generated by SolidActions SDK. DO NOT EDIT.
// Regenerate this file after updating solidactions.yaml.`;

/**
 * Emit a TypeScript declaration file text that augments `InvokeCtxVarsAugment`
 * with the project's typed var names.
 *
 * - Plain env vars → `VarName: string`
 * - OAuth connection vars → `VarName: ConnectionVar`
 * - Empty declarations → a syntactically valid file with an empty interface.
 */
export function generateVarsTypes(declarations: VarsDeclarations): string {
  const { vars, connections } = declarations;

  const lines: string[] = [];

  // Individual property lines inside the GeneratedVars interface body
  for (const name of vars) {
    lines.push(`  ${name}: string;`);
  }
  for (const name of connections) {
    lines.push(`  ${name}: ConnectionVar;`);
  }

  const interfaceBody = lines.length > 0 ? '\n' + lines.join('\n') + '\n' : '';

  const needsConnectionVarImport = connections.length > 0;
  const importLine = needsConnectionVarImport ? `import type { ConnectionVar } from '@solidactions/sdk';\n\n` : '';

  return [
    BANNER,
    '',
    `${importLine}export interface GeneratedVars {${interfaceBody}}`,
    '',
    `declare module '@solidactions/sdk' {`,
    `  interface InvokeCtxVarsAugment extends GeneratedVars {}`,
    `}`,
    '',
  ].join('\n');
}
